name: Send slack message for a build
description: Send slack message for a build
inputs:
  environment:
    description: The environment name
    required: true
  issue-identifier:
    description: The identifier of the issue
    required: true
  issue-title:
    description: The title of the issue
    required: true
  issue-url:
    description: The url of the issue
    required: true
outputs:
  description:
    description: The description of the pull request
    value: ${{ steps.update-description.outputs.description }}  
  title:
    description: The title of the pull request
    value: ${{ steps.create-title.outputs.title }}

runs:
  using: composite
  steps:
    - name: Get PR#${{ github.event.pull_request.number }} description
      id: get-pr-description
      shell: bash
      run: |
        DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body' --repo '${{ github.repository }}')
        echo "description<<EOF" >> $GITHUB_OUTPUT
        echo "$DESCRIPTION" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Create PR#${{ github.event.pull_request.number }} title
      id: create-title
      shell: bash
      run: |
        BRANCH_NAME="${{ github.head_ref }}"
        BRANCH_NAME_LOWERCASE="${BRANCH_NAME,}"
        TYPE=$(echo "$BRANCH_NAME_LOWERCASE" | cut -d'/' -f1)
        
        PULL_REQUEST_TITLE=""
        if [[ "${{ inputs.issue-identifier }}" == "" && "${{ inputs.issue-title }}" == "" ]]; then
          PULL_REQUEST_TITLE="merge:${{ github.head_ref }} to ${{ github.base_ref }}"
        else
          PULL_REQUEST_TITLE="$TYPE:[${{ inputs.issue-identifier }}] ${{ inputs.issue-title }}"
        fi

        echo "title=$PULL_REQUEST_TITLE" >> $GITHUB_OUTPUT
    - name: Update PR#${{ github.event.pull_request.number }} description
      id: update-description
      shell: bash
      run: |
        if [[ "${{ inputs.issue-identifier }}" == "" && "${{ inputs.issue-title }}" == "" ]]; then
          echo "description=# ${{ github.base_ref }}" >> $GITHUB_OUTPUT
        else
          ISSUE_IDENTIFIER="${{ inputs.issue-identifier }}"
          ISSUE_TITLE="${{ inputs.issue-title }}"
          ISSUE_URL="${{ inputs.issue-url }}"
      
          ENVIRONMENT="${{ inputs.environment }}"
      
          REPOSITORY_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.head_ref }}"
          DESCRIPTION="${{ steps.get-pr-description.outputs.description }}"
      
          DESCRIPTION=$(sed -e "s|{{ISSUE_IDENTIFIER}}|$ISSUE_IDENTIFIER|g" \
          -e "s|{{ISSUE_TITLE}}|${ISSUE_TITLE//&/\\&}|g" \
          -e "s|{{ISSUE_URL}}|${ISSUE_URL//&/\\&}|g" \
          -e "s|{{REPOSITORY_NAME}}|$REPOSITORY_NAME|g" \
          -e "s|{{ENVIRONMENT}}|$ENVIRONMENT|g" \
          -e "s|{{BRANCH_NAME}}|$BRANCH_NAME|g" <<< $DESCRIPTION)
      
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
    - name: Apply PR#${{ github.event.pull_request.number }} changes
      shell: bash
      run: |
        gh pr edit ${{ github.event.pull_request.number }} --title '${{ steps.create-title.outputs.title }}' --body '${{ steps.update-description.outputs.description }}' --repo '${{ github.repository }}'
      env:
        GH_TOKEN: ${{ github.token }}
