name: Create tag
description: Create tag
inputs:
  tag-name:
    description: The name of the tag
    required: true

runs:
  using: composite
  steps:
    - name: Does tag exist
      shell: bash
      id: does-tag-exist
      run: |
        if [ $(git tag -l "${{ inputs.tag-name }}") ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    - name: Setup git user
      shell: bash
      if: ${{ success() && steps.does-tag-exist.outputs.exists == 'true' }}
      run: |
        git config user.name '${{ github.actor }}'
        git config user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}
    - name: Create tag
      shell: bash
      if: ${{ success() && steps.does-tag-exist.outputs.exists == 'true' }}
      run: git tag ${{ inputs.tag-name }}
    - name: Push tag
      shell: bash
      if: ${{ success() && steps.does-tag-exist.outputs.exists == 'true' }}
      run: git push --tags